Rocket/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Rocket.Models;
using Rocket.Data;

namespace Rocket.Controllers
{
    public class FilesController : Controller
    {
        private readonly RocketContext _context;

        //Constructor
        public FilesController(RocketContext context)
        {
            _context = context;
        }

        //Files Home
        public IActionResult Index()
        {
            //Attempt to login, create account if not existing
            String mySystemName = System.Security.Principal.WindowsIdentity.GetCurrent().Name;
            String myUserName = mySystemName.Split('\\')[1];
            Account myAccount = _context.Account.Where(i => i.accountName == myUserName).Single();

            ViewData["User"] = myAccount;
            ViewData["Username"] = myAccount.accountName;
            ViewData["UserAvatar"] = myAccount.accountAvatar + ".png";
            ViewData["SelectedTab"] = 2;

            return View();
        }
    }
}

Rocket/Views/Shared/_Layout.cshtml
<!--Variables-->
@{

    //Greeting
    #region Greeting

    String greeting = "Hi, ";
    String mySystemName = System.Security.Principal.WindowsIdentity.GetCurrent().Name;
    String myUserName = mySystemName.Split('\\')[1];

    int thisHour = DateTime.Now.Hour;
    var thisTime = DateTime.Now.ToString("t");

    if ((thisHour >= 0) && (thisHour < 12))
    {
        greeting = "Morning, " + myUserName + "! " + "It's " + thisTime + ".";
    }
    else if ((thisHour >= 12) && (thisHour < 18))
    {
        greeting = "Afternoon, " + myUserName + "! " + "It's " + thisTime + ".";
    }
    else if (thisHour >= 18 && (DateTime.Today.Hour <= 23))
    {
        greeting = "Evening, " + myUserName + "! " + "It's " + thisTime + ".";
    }
    else
    {
        greeting = "Hi, " + myUserName + "! " + "It's " + thisTime + ".";
    }

    #endregion

    //Selected Tab
    int navTab = (int)ViewData["SelectedTab"];
    <div id="selectTab" tabNumber="@navTab"></div>

    //User Variables
    #region User Specifics

    var myUserInstance = (Account)ViewData["User"];
    String userAvatar = (String)ViewData["UserAvatar"];

    <!--Tabs-->

    String[] tabColours;
    String tabText;
    switch (myUserInstance.accountTabs)
    {
        case "Rainbow":
            tabColours = new String[] { "red", "dodgerblue", "limegreen", "darkorange", "purple" };
            tabText = "rgb(255, 255, 255)";
            break;
        case "Metal":
            tabColours = new String[] { "rgb(70, 70, 70)", "rgb(70, 70, 70)", "rgb(70, 70, 70)", "rgb(70, 70, 70)", "rgb(70, 70, 70)" };
            tabText = "rgb(255, 255, 255)";
            break;
        case "Snow":
            tabColours = new String[] { "rgb(255, 255, 255)", "rgb(255, 255, 255)", "rgb(255, 255, 255)", "rgb(255, 255, 255)", "rgb(255, 255, 255)" };
            tabText = "rgb(0, 0, 0)";
            break;
        case "Seamless":
            tabColours = new String[] { "rgb(30, 30, 30)", "rgb(30, 30, 30)", "rgb(30, 30, 30)", "rgb(30, 30, 30)", "rgb(30, 30, 30)" };
            tabText = "rgb(255, 255, 255)";
            break;
        default:
            tabText = "rgb(255, 255, 255)";
            tabColours = new String[] { "red", "dodgerblue", "limegreen", "darkorange", "purple" };
            break;
    }

    <!--Body-->

    String myBody;
    switch (myUserInstance.accountTheme)
    {
        case "Light":
            myBody = "rgb(250, 250, 250)";
            break;
        case "Dark":
            myBody = "rgb(20, 20, 20)";
            break;
        case "Blue":
            myBody = "rgb(204, 235, 255)";
            break;
        default:
            myBody = "rgb(220, 220, 220)";
            break;
    }

    #endregion

}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rocket</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="background-color: @myBody">

    <!--Navigation bar-->
    <div class="site_navbar">

        <!--Logo-->
        <div class="site_logo">
            <img src="~/images/Logo/rocket_blank.png" />
        </div>

        <!--Menu-->
        <a asp-controller="Home" asp-action="Index">
            <div class="site_navtab @myUserInstance.accountTabs" style="background-color:@tabColours[0]; color: @tabText">Home</div>
        </a>
        <a asp-controller="Settings" asp-action="Index">
            <div class="site_navtab @myUserInstance.accountTabs" style="background-color: @tabColours[1]; color: @tabText">Settings</div>
        </a>
        <a asp-controller="Files" asp-action="Index">
            <div class="site_navtab @myUserInstance.accountTabs" style="background-color: @tabColours[2]; color: @tabText">Files</div>
        </a>
        <a asp-controller="Talk" asp-action="Index">
            <div class="site_navtab @myUserInstance.accountTabs" style="background-color: @tabColours[3]; color: @tabText">Talk</div>
        </a>
        @if (myUserName == "Dan")
        {
            <a asp-controller="Manage" asp-action="Index">
                <div class="site_navtab @myUserInstance.accountTabs" style="background-color: @tabColours[4]; color: @tabText">Manage</div>
            </a>
        }


        <!--Username, Avatar-->
        <div class="site_userbox">
            <p class="site_greetingText" id="greetingText" heldTime="@greeting">@greeting</p>
            <img src="~/images/Avatar/@userAvatar" />
        </div>
    </div>

        <div class="container body-content">
            @RenderBody()
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
</body>
</html>